<a href="https://colab.research.google.com/github/AdityaKumar3594/Semester-3/blob/main/Lab%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*** Filter based methods***
    
     SelectKBest: It selects k highest scoring features based on a function and removes the rest of the features.
     Lets take an example of California Housing dataset.
     
     import numpy as np
     from sklearn.datasets import fetch_california_housing
     …………
1)download data and select a subset X_california[:2000, :], y_california[:2000]

2)Calculate Shape of feature matrix before feature selection

3)Select 3 most important features, since it is a regression problem, we can use only mutual_info_regression or f_regression scoring functions only. Calculate shape of feature matrix after feature selection






In [ ]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_regression,f_regression

In [ ]:
X_california = fetch_california_housing().data
y_california = fetch_california_housing().target

In [ ]:
X_subset = X_california[:2000, :]
y_subset = y_california[:2000]

In [ ]:
print(f"Shape of feature matrix before feature selection: {X_subset.shape}")
X_subset

Shape of feature matrix before feature selection: (2000, 8)


array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7829    ,   45.        ,    4.7       , ...,    3.56956522,
          36.73      , -119.77      ],
       [   1.5227    ,   39.        ,    4.20588235, ...,    4.52941176,
          36.75      , -119.77      ],
       [   1.5547    ,   20.        ,    4.18735892, ...,    2.46275395,
          36.74      , -119.77      ]])

In [ ]:
selector = SelectKBest(score_func=mutual_info_regression, k=3)
X_new = selector.fit_transform(X_subset, y_subset)

# Calculate the shape of the feature matrix after feature selection
print(f"Shape of feature matrix after feature selection: {X_new.shape}")
X_new



Shape of feature matrix after feature selection: (2000, 3)


array([[   8.3252,   37.88  , -122.23  ],
       [   8.3014,   37.86  , -122.22  ],
       [   7.2574,   37.85  , -122.24  ],
       ...,
       [   1.7829,   36.73  , -119.77  ],
       [   1.5227,   36.75  , -119.77  ],
       [   1.5547,   36.74  , -119.77  ]])

In [ ]:
f_selector = SelectKBest(score_func=f_regression, k=3)
X_new = f_selector.fit_transform(X_subset, y_subset)

# Calculate the shape of the feature matrix after feature selection
print(f"Shape of feature matrix after feature selection: {X_new.shape}")
X_new

Shape of feature matrix after feature selection: (2000, 3)


array([[   8.3252,   37.88  , -122.23  ],
       [   8.3014,   37.86  , -122.22  ],
       [   7.2574,   37.85  , -122.24  ],
       ...,
       [   1.7829,   36.73  , -119.77  ],
       [   1.5227,   36.75  , -119.77  ],
       [   1.5547,   36.74  , -119.77  ]])

    • SelectPercentile: This is very similar to SelectKBest from previous section, the only difference is, it selects top Percentile of
      all features and drops the rest of the features.
      Similar to SelectKBest, it also uses a scoring function to decide importance of features.Let's use the california housing price
      dataset also for this API and calculate top 30 percentile of features.

In [ ]:
from sklearn.feature_selection import SelectPercentile

In [ ]:
S_selector = SelectPercentile(score_func=mutual_info_regression, percentile=30)
X_new = S_selector.fit_transform(X_subset, y_subset)

# Calculate the shape of the feature matrix after feature selection
print(f"Shape of feature matrix after feature selection: {X_new.shape}")
X_new

Shape of feature matrix after feature selection: (2000, 3)


array([[   8.3252,   37.88  , -122.23  ],
       [   8.3014,   37.86  , -122.22  ],
       [   7.2574,   37.85  , -122.24  ],
       ...,
       [   1.7829,   36.73  , -119.77  ],
       [   1.5227,   36.75  , -119.77  ],
       [   1.5547,   36.74  , -119.77  ]])

    • Similarly apply GenericUnivariateSelect also for same number of features on the same dataset.


In [ ]:
from sklearn.feature_selection import GenericUnivariateSelect

GU_selector = GenericUnivariateSelect(score_func=mutual_info_regression, mode='k_best', param=3)
X_new = GU_selector.fit_transform(X_subset, y_subset)

# Calculate the shape of the feature matrix after feature selection
print(f"Shape of feature matrix after feature selection: {X_new.shape}")
X_new

Shape of feature matrix after feature selection: (2000, 3)


array([[   8.3252,   37.88  , -122.23  ],
       [   8.3014,   37.86  , -122.22  ],
       [   7.2574,   37.85  , -122.24  ],
       ...,
       [   1.7829,   36.73  , -119.77  ],
       [   1.5227,   36.75  , -119.77  ],
       [   1.5547,   36.74  , -119.77  ]])